-- DROP DATABASE IF EXISTS `sql_false_flag`;
-- CREATE DATABASE sql_false_flag;
use sql_false_flag;
-- DROP table IF EXISTS `After_Feedback_Groups1_Info` ;
-- create table `UsersProfile` ( -- `User_id` tinyint(8) NOT NULL ,`Username` varchar(128) NOT NULL,`Fullname` varchar(128) NOT NULL,`Location` varchar(86) ,`Description` LONGTEXT NOT NULL ,`Followers` bigint NOT NULL,`Following` bigint NOT NULL,`Join_Date` varchar(86) NOT NULL,`Verification_status` int NOT NULL,`Lists` int,`Likes` bigint,`Birthday` varchar(86)  ,`Profession` varchar(86),`Tweets` bigint NOT NULL,`Website` varchar(128) )ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;    
-- select * from UsersProfile;
-- drop table UsersTweets_Temp;
-- create table `UsersTweets_Temp` ( `Datetime` varchar(128) NOT NULL,	`Tweet_Id` BIGINT NOT NULL,`tweet_text` LONGTEXT NOT NULL , `Username` varchar(86) NOT NULL)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
-- select * from UsersTweets_Temp;
-- create table `Groups1_Info` (`Username` varchar(128), `Usernames` varchar(255),`Keywords` LONGTEXT,`Fullname` varchar(255) )ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; 
-- create table `After_Feedback_Groups1_Infusersprofile_tempusersprofile_tempafter_feedback_groups1_infoo` (`Username` varchar(128), `Usernames` LONGTEXT,`Keywords` LONGTEXT,`Fullname` LONGTEXT )ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; 
-- create table `Feed_Back_Groups1_Info` (`Fullname` varchar(128), `description` LONGTEXT,`ID_twitter` varchar(255),`Website` varchar(255),`ID_Youtube` varchar(255),`ID_Instagram` varchar(255),`ID_Facebook` varchar(255),`folder-name` varchar(255))ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
-- create table `Feed_Back_Groups1_Info` (`Fullname` varchar(128), `description` LONGTEXT,`ID_twitter` varchar(255),`User_Pics` varchar(255))ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
-- DROP table `Google_Check`;--  (`ID_twitter` varchar(255))ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
-- ALTER TABLE UsersProfile MODIFY column_name INT AUTO_INCREMENT;
-- create table `Sentiments`(`Username` varchar(255), `Positive` varchar(255) ,`Negative` varchar(255),`Neutral` varchar(255),`Overall` varchar(255))ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
select * from Feed_Back_Groups1_Info;
select * from UsersProfile_Temp;
-- select * from UsersProfile;
select * from Groups1_Info;
select * from After_Feedback_Groups1_Info;
-- select * from UsersTweets;
-- select * from UsersTweets_Temp;
select * from Sentiments;
-- select * from Pics_Grouping;
-- select description from UsersProfile WHERE Fullname LIKE '%imran%';
-- create table `Pics_Grouping`(`Username` varchar(128), `Usernames` LONGTEXT)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; 
-- SELECT `tweet_text` from UsersTweets_Temp where Username = 'otherjoebiden';
-- truncate table After_Feedback_Groups1_Info;